apiVersion: v1
kind: Pod
metadata:
  name: token-test
spec:
  serviceAccount: wordpress
  serviceAccountName: wordpress
  containers:
  - name: token-test
    image: pmvk/aws-token-test:latest
    imagePullPolicy: Always
    env:
    - name: AWS_ROLE_ARN
      value: "arn:aws:iam::044559835262:role/wordpress-sa"
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
    - name: WAIT_TIME_IN_SECONDS
      value: "120"
    volumeMounts:
    - mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
      name: aws-token
  volumes:
  - name: aws-token
    projected:
      sources:
      - serviceAccountToken:
          audience: "sts.amazonaws.com"
          expirationSeconds: 600 
          path: token
